name: Auto Generate Data

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight UTC
  workflow_dispatch: # Allows manual triggering
  repository_dispatch:
    types: [trigger-build] # Optional: Specify event types to react to

permissions:
  contents: write # Grant write permission to the GITHUB_TOKEN for the contents scope

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    # Add a condition to only run if the event is schedule, dispatch, or the specific repository_dispatch type
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event.action == 'trigger-build'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Specify your project's Node.js version
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          # Check if there are any changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: auto-generate data [skip ci]"
            git push
          fi
